### ISSUE TITLE
Unknown device when HDMI Audio with AVR reconnects

### ISSUE THREAD

**Issue by RickDB** [xenolightning/AudioSwitcher#27]
Noticed this unknown device bug for a while in the AudioSwitcher windows app and in my MP1-Audioswitcher (Mediaportal plugin) recently as well.

**Steps to recreate**
- Start AudioSwitcher app
- Make HDMI audio device the default (Denon AVR in my case)
- Let the AVR go into standby or power off so that it does passthru HDMI signal
- Will still list HDMI audio device correctly.
- Now turn the AVR back on
- AudioSwitcher app will now list an device named "unknown" which can be set as active and is indeed the HDMI audio device just not with the proper name however with same device.id.

**Current workarounds**
- Restart AudioSwitcher app and it will no longer list the unknown device.
- In the case of MP1-Audioswitcher I have to reload the CoreAudio class like so as otherwise it would need an Mediaportal restart:

https://github.com/RickDB/MP1-AudioSwitcher/commit/a9d22e5928a3e1b1621ede5636d234e41fb3c2f0

Possible solution in AudioSwitcher library might be to always reload the CoreAudio class in case of unknown devices during .GetDevices call however that is more of workaround than an actual fix.
Or during the reloading of device lists in library internally it does it too quickly during reconnects and requires a longer delay for certain sources (HDMI audio in this case)

Library version installed via Nuget:

AudioSwitcher.AudioApi
v4.0.30319

OS:
Windows 10 x64

**Comment by xenolightning** [comment]
This is an awesome bug report btw. What HDMI source are you using? Onboard/nVidia/AMD/Other?

I should be able to exactly replicate this scenario, using my PC and AVR (Sony). HDMI audio will be via nVidia drivers.

I wonder if it's updating the name of the device before it's "Ready", and the properties haven't been made available.

**Comment by RickDB** [comment]
Thanks :) , here's the fulll setup:

**PC** source: nVidia GTX1080 (368.81 drivers)
**AVR** : Denon AVR-3313
**TV** : Sony Bravia W885B

Indeed looks like it's retrieving the device info too soon after reconnect as the AVR-3313 does take about 1-2s to completely return to normal, tried to reproduce it with some switching to other AVR sources (TV audio  / Console etc.) and coming back to the PC one but that worked properly with no unknown sources listed.

nVidia does have a driver issue in combination with Windows 10 and that is that it can list the HDMI sources differently from time to time even though it's the same output like so:

DENON-AVRHD-4 (NVIDIA High Definition Audio)

whereas sometimes it renames to the default one (after reboot most of the time):

DENON-AVRHD-0 (NVIDIA High Definition Audio)

**Comment by xenolightning** [comment]
Have tested this with my MBP outputting audio over HDMI.

Using Intel on-board HD4000 (I think), the device seemed to be fine. 

I'll see if I can find my larger HDMI cable to test nvidia hdmi audio, it might be something to do with nvidia devices alone.

The renaming issue is likely to be as a result of the device being identified as "new", this can happen with USB devices too. If you unplug a device, and plug it into a different port, it will do something similar.

I see you've got some C#/.NET experience (looking through your repo's), if I can't get to the bottom of it, would you be able to clone, and debug the api locally?

**Comment by RickDB** [comment]
Yeah no problem debugging the API locally, would only need a few pointers on where in code to extract proper debug info and such :)

**Comment by xenolightning** [comment]
Yeah for sure. It's probably in or around: https://github.com/xenolightning/AudioSwitcher/blob/async_452/AudioSwitcher.AudioApi.CoreAudio/CoreAudioDevice.cs#L514

That's where the system sends events to the devices, and triggers a property update. 

The Name's are "Unknown" when the properties doesn't hold a value for the device names. Check out the device properties accessors here:

https://github.com/xenolightning/AudioSwitcher/blob/async_452/AudioSwitcher.AudioApi.CoreAudio/CoreAudioDevice.cs#L91

**Comment by xenolightning** [comment]
@RickDB I just had an epiphany!

Device Properties and Device State, are currently triggered by two different events.

To prevent unexpected behaviour I prevent  properties from being loaded when the device is unplugged/notpresent/disabled. Which is why the name is "unknown" to begin with.

Now when the device connects, I assumed that it would fire the updated properties event, but it may not.

But it certainly fires the device state changed.

The solution might be as simple as reloading properties when the device state changes!

I'll link a commit here, and fire up a nuget build.

**Comment by xenolightning** [comment]
https://github.com/xenolightning/AudioSwitcher/commit/14f87629b2b4bc78cc069726907ee91ef7bd7ac2

**Comment by xenolightning** [comment]
https://www.nuget.org/packages/AudioSwitcher.AudioApi/4.0.0-alpha2
https://www.nuget.org/packages/AudioSwitcher.AudioApi.CoreAudio/4.0.0-alpha3

@RickDB  Just FYI, I "broke" a bunch of things since the alpha1. Many synchronous functions were removed in favour of async. Check out https://github.com/xenolightning/AudioSwitcher/commit/2ac8df7006cf8c6eb1d7b9f86806584126189cb3 for more detailed changes. IDevice & IAudioSession

**Comment by RickDB** [comment]
Thanks, upgrading the Mediaportal addon which uses those libraries for testing here and also does a lot of resume / standby actions so should pop up sooner if still the case that is :)

Some methods got different naming however like this:

CoreAudioController -> SetDefaultDevice(device);

That seems no longer valid as it has no setter, did that method get replaced with a different class or method?

**Comment by xenolightning** [comment]
Awesome. Ta. This release includes the largest change to the api in a long while, it's no longer limited by one thread to do all the system functions, so it should be "faster" on systems which have a lot of devices.

RE: `SetDefaultDevice`. Yeah, there were two places to set the default device. And it wasn't clear exactly how they worked, so I dropped the controller one in favour of keeping it on IDevice. It seemed like a better fit for the function because it happens "on the device"

**Comment by xenolightning** [comment]
@RickDB There's a couple more minor changes coming.

I spotted a few things that could be improved, so I'll fire them in, and probably release a 4.0beta, followed closely by the 4.0 full.

**Comment by RickDB** [comment]
No issues whatsoever with devices 👍 , only downside is the 4.5.2 requirement for Mediaportal as that comes with 4.0 by default but will just supply it with the plugin installer :)

**Comment by xenolightning** [comment]
It probably can compile down to 4.0.

I'll have quick look now, might be able to do a dual release with a dependency on Async.Bcl

**Comment by xenolightning** [comment]
Yeah looks like it will work with any trouble.

I'll update the csproj tonight, and ship another nuget build with 4.0 and 4.5.2 support

**Comment by xenolightning** [comment]
A few minor changes: https://github.com/xenolightning/AudioSwitcher/commit/75dc4b242f0c4246e99ea2fbb1767a8f0386ff3e

That commit has the full changeset for backwards 4.0 support using Bcl.Async.

The tests aren't run under NET4 yet, I'll evaluate whether I want to do that. It's probably fairly useful.

**Comment by RickDB** [comment]
Awesome :D
Once API beta is out will include in next plugin release for users 👍

**Comment by xenolightning** [comment]
https://www.nuget.org/packages/AudioSwitcher.AudioApi.CoreAudio/4.0.0-alpha5

Still alpha, but includes the multi target support.

It's only alpha because I intend to change some of the `IDeviceCapability` extensions, but it's all good to use the core functionality (none of the device capabilities have been done yet anyway)

**Comment by RickDB** [comment]
Ah nice so good to go for the plugin then, will re-compile here with that one and test.

**Comment by RickDB** [comment]
Prepping a new plugin release using alpha 5 CoreAudio here but seems there's reference to:

System.Runtime 2.6.10

Which when I use .NET 4.0 as the target framework reports a mismatch:

``
The primary reference "AudioSwitcher.AudioApi.CoreAudio, Version=4.0.0.308, Culture=neutral, PublicKeyToken=fda5729e2db3a64f, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "AudioSwitcher.AudioApi.CoreAudio, Version=4.0.0.308, Culture=neutral, PublicKeyToken=fda5729e2db3a64f, processorArchitecture=MSIL" or retarget your application to a framework version which contains "System.Runtime, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".	MP1-AudioSwitcher		
``

**Comment by xenolightning** [comment]
Quickest fix is to update the BCL nuget packages pulled in from the net4 nuget package.

I had noticed it, and there is a commit to fix it: https://github.com/xenolightning/AudioSwitcher/commit/3c06b74c4d8b5e02221bb2cc37400fca6f27172a

Just not released via nuget yet.

A working packages.config:
`  <package id="AudioSwitcher.AudioApi" version="4.0.0-alpha5" targetFramework="net40" />
  <package id="AudioSwitcher.AudioApi.CoreAudio" version="4.0.0-alpha5" targetFramework="net40" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net40" />
  <package id="Microsoft.Bcl.Async" version="1.0.168" targetFramework="net40" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net40" />`

**Comment by RickDB** [comment]
Yeah just did the update and compiles fine  👍

**Comment by xenolightning** [comment]
Yeah bit of an oddity in the way nuget works.

Always pulls in the lowest possible package, so since I only depend directly on the Bcl.Async package, and the others are further down the dependency chain it just chooses the lowest.

The net40 build was originally done against the latest packages, and I didn't realise it bound the version of those assemblies. Shouldn't be a problem for any newer builds

**Comment by RickDB** [comment]
Updated Mediaportal plugin for AudioSwitcher and pushed to users, looks good during testing and used ILMerge to make everything neatly packed as otherwise you have to ship it with System.Threading.Tasks for instance :)
Will let you know if I get any bug reports.

**Comment by RickDB** [comment]
Nothing reported by users so think it's safe to say that this issue is resolved 👍 , thanks again for the improvements and fixes!

**Comment by xenolightning** [comment]
Awesome, that's good news for the initial release of 4.0.0. It should be pretty stable :+1: 

No problem!
